### PR TITLE
#[160183423] User(admin) should be able edit available food items 

### PR DESCRIPTION
**Pull request by mdn-network**
#### What does this PR do?

- Enables admin to edit/remove foods from the main orders

#### Description of Task to be completed?

- Added a table with the required columns and rows to enable Admin to

#### How should this be manually tested?
-Clone the repo from [here](https://github.com/Philipotieno/Fast-Food/tree/ft-admin-roles-160183423)

- Go to UI and open edit.html with your favorite browser 

#### What are the relevant pivotal tracker stories?

- #[160183423](https://www.pivotaltracker.com/n/projects/2194623)

#### Screenshots
edit

### CODE REVIEW

**Comment by TeamoreA** [comment]
The UI looks good

**Comment by mdn-network** [comment]
Thank you @TeamoreA

**Comment by ogol254** [comment]
Philip this looks good. Go ahead and merge

**Comment by mdn-network** [comment]
@ogol254 Thank you

**Pull request merged**
