### PR TITLE
[#160192891] Index page

### PR DESCRIPTION
**Pull request by mdn-network**
#### What does this PR do?

- Enables user to either register or log in

#### Description of Task to be completed?

- Building the landing page using css and html

#### How should this be manually tested?

- [clone](https://github.com/Philipotieno/Fast-Food) the repo
- Extract it and navigate to UI where you will find an index.html file
- open the index.html file using your favorite browser 
#### Any background context you want to provide?
-Doesn't implement the core functionality yet
#### What are the relevant pivotal tracker stories?
-[#160192891](https://www.pivotaltracker.com/n/projects/2194623)
#### Screenshots 
screenshot1bt

### CODE REVIEW

**Comment by SilasKenneth** [comment]
Good design man, could you get a better color for the blue text? just for readablity

**Comment by mdn-network** [comment]
Thsnks @SilasKenneth lemme work on it

**Comment by Darius-Ndubi** [comment]
Nice one, You can use gradients too to blur out the background and make text readable to keep your colors

**Comment by mdn-network** [comment]
@Darius-Ndubi Thank you lemme fix that

**Comment by EmmanuelBeja** [comment]
'login in you have an account' doesn't make sense. otherwise nice work

**Pull request merged**
